#!/bin/bash

#build a board type
build_uf2()
{
  board=$1"board .."
  uf2="picozx81_"$1".uf2"

  cmake -DHDMI_SOUND=OFF -DPICO_BOARD=${board}
  make -j4
  cp ./${uf2} ../uf2/${uf2}
}

build_uf2_hdmi()
{
  board=$1"board .."
  uf2="picozx81_"$1"_hdmi_sound.uf2"

  cmake -DHDMI_SOUND=ON -DPICO_BOARD=${board}
  make -j4
  cp ./${uf2} ../uf2/${uf2}
}
# Create the directories
mkdir -p build
mkdir -p uf2
cd build

# Build all PicoZX81 variants
build_uf2 vga
build_uf2 dvi
build_uf2 picomitevga
build_uf2 olimexpc
build_uf2 vga332
build_uf2 lcdws28
build_uf2_hdmi dvi
build_uf2_hdmi olimexpc
