#!/bin/bash
set -e  # Ensures the script exits on failure

# Get the build type
build_type() {
  echo "Release"  # Can be expanded for future variations
}

# Centralized function for CMake and Build
run_cmake_and_build() {
  local board=$1"board .."
  local chip_type=$2
  local hdmi=$3
  local lcd=$4
  local uf2="picozx81_${1}_$( [[ "$hdmi" == "ON" ]] && echo "hdmi_sound_" )$( [[ "$lcd" == "ON" ]] && echo "lcd_" )${chip_type}.uf2"

  cmake -DHDMI_SOUND=$hdmi -DPICOZX_LCD=$lcd -DCMAKE_BUILD_TYPE=$(build_type "$chip_type") -DTIME_SPARE=OFF -DFLASH_LED=OFF -DPICO_BOARD=$board -DPICO_MCU=$chip_type
  make -j4 2>&1 | tee -a ../build.log

  # Check for errors and warnings - excluding the target errors step in picotoolBuild
  if grep -iE "error|warning" ../build.log | grep -v "Built target errors"; then
    echo "Build failed due to errors or warnings."
    exit 1
  fi

  cp ./${uf2} ../uf2/${uf2}
}

# Functions for different build variants
build_uf2() {
  run_cmake_and_build "$1" "$2" OFF OFF
}

build_uf2_hdmi() {
  run_cmake_and_build "$1" "$2" ON OFF
}

build_uf2_lcd() {
  run_cmake_and_build "$1" "$2" OFF ON
}

# Create the directories from scratch
rm -rf build_2040 build_2350
mkdir build_2040 build_2350 uf2

# Create the build directory
rm -f build.log
touch build.log

# Build all PicoZX81 variants for rp2040
cd build_2040

build_uf2 vga rp2040
build_uf2 dvi rp2040
build_uf2 picomitevga rp2040
build_uf2 olimexpc rp2040
build_uf2 vga332 rp2040
build_uf2 vgamaker222c rp2040
build_uf2 lcdws28 rp2040
build_uf2 lcdmaker rp2040
build_uf2 picozx rp2040
build_uf2 picozxreal rp2040
build_uf2_hdmi dvi rp2040
build_uf2_hdmi olimexpc rp2040
build_uf2_hdmi wspizero rp2040
build_uf2_lcd picozx rp2040

# Build all PicoZX81 variants for rp2350
cd ../build_2350

build_uf2 vga rp2350
build_uf2 dvi rp2350
build_uf2 picomitevga rp2350
build_uf2 olimexpc rp2350
build_uf2 vga332 rp2350
build_uf2 lcdws28 rp2350
build_uf2_hdmi dvi rp2350
build_uf2_hdmi olimexpc rp2350
