// -----------------------------------------------------
// NOTE: THIS HEADER IS ALSO INCLUDED BY ASSEMBLER SO
//       SHOULD ONLY CONSIST OF PREPROCESSOR DIRECTIVES
// -----------------------------------------------------

#ifndef _BOARDS_VGAMAKERBOARD222C_H
#define _BOARDS_VGAMAKERBOARD222C_H

// For board detection
#define RASPBERRYPI_VGAMAKERBOARD222C

#define VGAMAKERBOARD222C_VGA_COLOR_PIN_BASE 0
#define VGAMAKERBOARD222C_VGA_SYNC_PIN_BASE 6

#define VGAMAKERBOARD222C_PWM_L_PIN  18
#define VGAMAKERBOARD222C_PWM_R_PIN  19

#define VGAMAKERBOARD222C_SD_CLK_PIN  10
#define VGAMAKERBOARD222C_SD_CMD_PIN  11    // MOSI
#define VGAMAKERBOARD222C_SD_DAT0_PIN 12    // MISO
#define VGAMAKERBOARD222C_SD_CS_PIN   15


#ifndef PICO_SCANVIDEO_COLOR_PIN_BASE
#define PICO_SCANVIDEO_COLOR_PIN_BASE VGAMAKERBOARD222C_VGA_COLOR_PIN_BASE
#endif

#ifndef PICO_SCANVIDEO_SYNC_PIN_BASE
#define PICO_SCANVIDEO_SYNC_PIN_BASE VGAMAKERBOARD222C_VGA_SYNC_PIN_BASE
#endif

#define PICO_SCANVIDEO_ENABLE_CLOCK_PIN 0
#define PICO_SCANVIDEO_COLOR_PIN_COUNT 6
#define PICO_SCANVIDEO_PIXEL_RSHIFT 4
#define PICO_SCANVIDEO_PIXEL_GSHIFT 2
#define PICO_SCANVIDEO_PIXEL_BSHIFT 0
#define PICO_SCANVIDEO_PIXEL_RCOUNT 2
#define PICO_SCANVIDEO_PIXEL_GCOUNT 2
#define PICO_SCANVIDEO_PIXEL_BCOUNT 2

#ifndef PICO_AUDIO_PWM_L_PIN
#define PICO_AUDIO_PWM_L_PIN VGAMAKERBOARD222C_PWM_L_PIN
#endif

#ifndef PICO_AUDIO_PWM_R_PIN
#define PICO_AUDIO_PWM_R_PIN VGAMAKERBOARD222C_PWM_R_PIN
#endif

#ifndef PICO_SD_CLK_PIN
#define PICO_SD_CLK_PIN VGAMAKERBOARD222C_SD_CLK_PIN
#endif

#ifndef PICO_SD_CMD_PIN
#define PICO_SD_CMD_PIN VGAMAKERBOARD222C_SD_CMD_PIN
#endif

#ifndef PICO_SD_DAT0_PIN
#define PICO_SD_DAT0_PIN VGAMAKERBOARD222C_SD_DAT0_PIN
#endif

#ifndef PICO_SD_CS_PIN
#define PICO_SD_CS_PIN VGAMAKERBOARD222C_SD_CS_PIN
#endif

// Move UART
#define PICO_DEFAULT_UART 0
#define PICO_DEFAULT_UART_TX_PIN 16
#define PICO_DEFAULT_UART_RX_PIN 17

#define PICO_VGAMAKER222C_BOARD

// Maker board has a Pico on it, so default anything we haven't set above
#include "boards/pico.h"

#endif
