name: Build UF2 Files with Raspberry Pi Pico SDK

on:
  push:
    branches:
      - test-actions  # Ensures workflow runs when changes are pushed to this branch
  pull_request:
    branches:
      - main  # Also runs when a PR is opened against main
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0  # Ensures submodules are checked out at the correct commit

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake ninja-build git

      - name: Install Raspberry Pi Pico SDK and Extras
        run: |
          mkdir -p ~/pico
          cd ~/pico
          git clone --depth=1 https://github.com/raspberrypi/pico-sdk.git
          git clone --depth=1 https://github.com/raspberrypi/pico-extras.git
          cd pico-sdk && git submodule update --init
          cd ../pico-extras && git submodule update --init

      - name: Set Environment Variables
        run: |
          echo "PICO_SDK_PATH=$HOME/pico/pico-sdk" >> $GITHUB_ENV
          echo "PICO_EXTRAS_PATH=$HOME/pico/pico-extras" >> $GITHUB_ENV

      - name: Verify PICO_SDK_PATH
        run: ls -l $PICO_SDK_PATH/external/pico_sdk_import.cmake

      - name: Make build script executable
        run: chmod +x buildall

      - name: Run CMake with PICO_SDK_PATH
        run: cmake -DPICO_SDK_PATH=$PICO_SDK_PATH ..

      - name: Run build script
        run: ./buildall

      - name: Upload UF2 artifacts only
        uses: actions/upload-artifact@v4
        with:
          name: uf2-files
          path: |
            build_2040/*.uf2
            build_2350/*.uf2
